config/routes.rb
Rails.application.routes.draw do

  match '/client/*path', to: 'client#index', via: :all
  match '/client/', to: 'client#index', via: :all

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :auctions, only: [:index, :show, :create, :update, :destroy] do
        resources :bids, only: [:create, :destroy], shallow: true
      end
      resources :tokens, only: [:create]
      resources :users, only: [:create]
    end
    match '*unmatched_route', to: 'application#not_found', via: :all
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :index, :show]

  resources :auctions do
    resources :bids, only: [:create, :destroy], shallow: true
  end

  get('/', { to: 'auctions#index', as: :home })

end

app/models/auction.rb
class Auction < ApplicationRecord

  default_scope { order(created_at: :desc) }
  
  has_many :bids, dependent: :destroy
  has_many :bidders, through: :bids, source: :user #not really essential

  belongs_to :user

  validates :title, presence: true
  validates :reserve_price, presence: true
  validates :end_date, presence: true
end

app/controllers/api/v1/auctions_controller.rb
class Api::V1::AuctionsController < Api::ApplicationController
  before_action :authenticate_user!
  before_action :find_auction, only: [:update, :show, :destroy]
  before_action :authorize_user!, only: [:update, :destroy]
  def index
    @auctions = Auction.order(created_at: :desc)
    render json: Auction.all
  end

  def show
    render json: @auction
  end

  def create
    auction = Auction.new(auction_params)
    auction.user = current_user

    auction.save!
    render json: {id: auction.id}
  end

  def update
    if @auction.update(auction_params)
      render json: {id: @auction.id}
    else
      head :bad_request
    end
  end

  def destroy
    if @auction.destroy
      render json: Auction.all, status: 200
    else
      head :bad_request
    end
  end

  private
  def find_auction
    @auction = Auction.find params[:id]
  end

  def auction_params
    params.require(:auction).permit(:title, :details, :reserve_price, :end_date)
  end

  def authorize_user!
    unless can?(:crud, @auction)
      head :bad_request
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_auction, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @auction = Auction.new
  end

  def index
    @auctions = Auction.all.order(created_at: :desc)
    respond_to do |format|
      format.html { render }
      format.json { render json: @auctions }
      format.xml { render xml: @auctions }
    end

  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to @auction
    else
      render :new
    end
  end

  def show
    @bids = @auction.bids.order(created_at: :desc)
    @bid = Bid.new
  end

  def edit
  end

  def update
    if @auction.update(auction_params)
      redirect_to auction_path(@auction)
    else
      render :edit
    end
  end

  def destroy
    @auction.destroy
    redirect_to auctions_path
  end


  private

  def auction_params
    params.require(:auction).permit(:title, :details, :end_date, :reserve_price)
  end

  def find_auction
    @auction = Auction.find params[:id]
  end

  def authorize_user!
    unless can?(:crud, @auction)
      flash[:alert] = "Access Denied!"
      redirect_to home_path
    end
  end

end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :end_date %>
  <%= f.input :reserve_price %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/auctions/edit.html.erb
<h1>Edit Auction</h1>
<%= render 'form' %>

app/views/auctions/index.html.erb
<h1>All Auctions</h1>

<% @auctions.each do |auction| %>
  <div class="auction-list-item">
    <%= link_to auction.title, auction_path(auction)  %>
  </div>
<% end %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>
<%= render 'form' %>

app/views/auctions/show.html.erb
<h2><%= @auction.title %></h2>

<p><%= @auction.details %></p>
<p>By
  <% if @auction.user %>
    <%= @auction.user.full_name %>
  <% else %>
    <%= "[deleted]" %>
  <% end %>
</p>
<p><strong>Reserve Price: </strong><%= @auction.reserve_price %></p>

<p><strong>End Date: </strong><%= @auction.end_date.to_formatted_s %></p>

<% if can?(:crud, @auction) %>
  <%= link_to 'Edit', edit_auction_path(@auction) %>
  <%=
    link_to(
     'Delete',
     auction_path(@auction),
     method: :delete,
     data: {confirm: 'Are you sure?'}
    )
  %>
<% end %>

<%# If we want to create a form for a model that is nested in/belongs to another model, we
must give 'form_for' both models in an array as its arguments where the first element of
the array is the model instance that the second element belongs to. 👇🏽 %>
<%= simple_form_for [@auction, @bid] do |f| %>
  <% if @bid.errors.present? %>
    <p>
      <%= @bid.errors.full_messages.join(', ') %>
    </p>
  <% end %>
  <div>
    <%= f.input :bid_price, placeholder: 'Bid Price', label: false %>
  </div>

  <%= f.submit 'Bid' %>
<% end %>

<h2>Previous Bids</h2>
<div class="bid-list">
  <% @bids.each do |bid| %>
    <div class="bid-list-item">
      <p><%= number_to_currency(bid.bid_price) %></p>
      <p>By <%= bid.user&.full_name || "[deleted]" %></p>
      <p>
        <strong>Created At: </strong>
        <%=time_ago_in_words(bid.created_at)%> ago

      <% if can?(:destroy, bid) %>
        <%= link_to(
          'Delete',
          bid,
          data: {confirm: 'Are you sure?'},
          method: :delete
          ) %>
      <% end %>
      </p>
    </div>
  <% end %>
</div>