config/routes.rb
Rails.application.routes.draw do

  match '/client/*path', to: 'client#index', via: :all
  match '/client/', to: 'client#index', via: :all

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :auctions, only: [:index, :show, :create, :update, :destroy] do
        resources :bids, only: [:create, :destroy], shallow: true
      end
      resources :tokens, only: [:create]
      resources :users, only: [:create]
    end
    match '*unmatched_route', to: 'application#not_found', via: :all
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :index, :show]

  resources :auctions do
    resources :bids, only: [:create, :destroy], shallow: true
  end

  get('/', { to: 'auctions#index', as: :home })

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAuction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', home_path %>
      |
      <%= link_to 'New Auction', new_auction_path %>
      |
      <%= link_to 'Auctions', auctions_path %>
      |
      <% if user_signed_in? %>
        <span>Hello, <%= current_user.first_name %>!</span>
        |
        <%= link_to(
          'Sign Out',
          session_path,
          method: :delete,
          data: {confirm: 'Do you really want to sign out?'}
          ) %>
      <% else %>
        <%= link_to 'Sign In', new_session_path %>
        |
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
    </nav>
    <hr />
    <div class="container">
      <% if flash[:notice].present?%>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%=flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% elsif flash[:alert].present?%>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%=flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAuction</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag "client" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Open+Sans|Abril+Fatface" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>